use serde::{Serialize, Deserialize};
use std::string::String;
use std::hash::Hash;
use crate::error::ApiError;
#[derive(Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Clone, Copy)]
pub enum CountryISO {
    AIA,
    AFG,
    AGO,
    ALA,
    ALB,
    AND,
    ARE,
    ARG,
    ARM,
    ASM,
    ATG,
    AUS,
    AUT,
    AZE,
    BDI,
    BEL,
    BEN,
    BFA,
    BGD,
    BGR,
    BHR,
    BHS,
    BIH,
    BLR,
    BLZ,
    BOL,
    BRA,
    BRB,
    BRN,
    BTN,
    BWA,
    CAF,
    CAN,
    CHE,
    CHL,
    CHN,
    CMR,
    COD,
    COG,
    COL,
    COM,
    CPV,
    CRI,
    CUB,
    CYP,
    CZE,
    DEU,
    DJI,
    DMA,
    DNK,
    DOM,
    DZA,
    ECU,
    EGY,
    ERI,
    ESP,
    EST,
    ETH,
    FIN,
    FJI,
    FRA,
    FSM,
    GAB,
    GBR,
    GEO,
    GHA,
    GIN,
    GMB,
    GNB,
    GNQ,
    GRC,
    GRD,
    GTM,
    GUY,
    HKG,
    HND,
    HRV,
    HTI,
    HUN,
    IDN,
    IND,
    IRL,
    IRN,
    IRQ,
    ISL,
    ISR,
    ITA,
    JAM,
    JOR,
    JPN,
    KAZ,
    KEN,
    KGZ,
    KHM,
    KIR,
    KNA,
    KOR,
    KWT,
    LAO,
    LBN,
    LBR,
    LBY,
    LCA,
    LIE,
    LKA,
    LSO,
    LTU,
    LUX,
    LVA,
    MAR,
    MCO,
    MDA,
    MDG,
    MDV,
    MEX,
    MHL,
    MKD,
    MLI,
    MLT,
    MMR,
    MNG,
    MNE,
    MOZ,
    MRT,
    MUS,
    MWI,
    MYS,
    NAM,
    NER,
    NGA,
    NIC,
    NLD,
    NOR,
    NPL,
    NRU,
    NZL,
    OMN,
    PAK,
    PAN,
    PER,
    PHL,
    PLW,
    PNG,
    POL,
    PRT,
    PRY,
    QAT,
    ROU,
    RUS,
    RWA,
    SAU,
    SDN,
    SEN,
    SGP,
    SLB,
    SLE,
    SLV,
    SMR,
    SOM,
    SRB,
    SSD,
    STP,
    SUR,
    SVK,
    SVN,
    SWE,
    SWZ,
    SYC,
    SYR,
    TCD,
    TGO,
    THA,
    TJK,
    TKM,
    TLS,
    TON,
    TTO,
    TUN,
    TUR,
    TUV,
    TZA,
    UGA,
    UKR,
    URY,
    USA,
    UZB,
    VEN,
    VCT,
    VNM,
    VUT,
    WSM,
    YEM,
    ZAF,
    ZMB,
    ZWE,
}

pub fn country_iso_to_text(country_iso: CountryISO) -> String {
    format!("{:?}", country_iso)
}

pub fn text_db_to_country_iso(text: &str) -> Result<CountryISO, ApiError> {
    match text {
        "AIA" => Ok(CountryISO::AIA),
        "AFG" => Ok(CountryISO::AFG),
        "ASM" => Ok(CountryISO::ASM),
        "ALB" => Ok(CountryISO::ALB),
        "ALA" => Ok(CountryISO::ALA),
        "DZA" => Ok(CountryISO::DZA),
        "AND" => Ok(CountryISO::AND),
        "AGO" => Ok(CountryISO::AGO),
        "ARG" => Ok(CountryISO::ARG),
        "ARM" => Ok(CountryISO::ARM),
        "AUS" => Ok(CountryISO::AUS),
        "AUT" => Ok(CountryISO::AUT),
        "AZE" => Ok(CountryISO::AZE),
        "BHS" => Ok(CountryISO::BHS),
        "BHR" => Ok(CountryISO::BHR),
        "BGD" => Ok(CountryISO::BGD),
        "BRB" => Ok(CountryISO::BRB),
        "BLR" => Ok(CountryISO::BLR),
        "BEL" => Ok(CountryISO::BEL),
        "BLZ" => Ok(CountryISO::BLZ),
        "BEN" => Ok(CountryISO::BEN),
        "BTN" => Ok(CountryISO::BTN),
        "BOL" => Ok(CountryISO::BOL),
        "BIH" => Ok(CountryISO::BIH),
        "BWA" => Ok(CountryISO::BWA),
        "BRA" => Ok(CountryISO::BRA),
        "BRN" => Ok(CountryISO::BRN),
        "BGR" => Ok(CountryISO::BGR),
        "BFA" => Ok(CountryISO::BFA),
        "BDI" => Ok(CountryISO::BDI),
        "CPV" => Ok(CountryISO::CPV),
        "KHM" => Ok(CountryISO::KHM),
        "CMR" => Ok(CountryISO::CMR),
        "CAN" => Ok(CountryISO::CAN),
        "CAF" => Ok(CountryISO::CAF),
        "TCD" => Ok(CountryISO::TCD),
        "CHL" => Ok(CountryISO::CHL),
        "CHN" => Ok(CountryISO::CHN),
        "COL" => Ok(CountryISO::COL),
        "COM" => Ok(CountryISO::COM),
        "COG" => Ok(CountryISO::COG),
        "CRI" => Ok(CountryISO::CRI),
        "HRV" => Ok(CountryISO::HRV),
        "CUB" => Ok(CountryISO::CUB),
        "CYP" => Ok(CountryISO::CYP),
        "CZE" => Ok(CountryISO::CZE),
        "COD" => Ok(CountryISO::COD),
        "DNK" => Ok(CountryISO::DNK),
        "DJI" => Ok(CountryISO::DJI),
        "DMA" => Ok(CountryISO::DMA),
        "DOM" => Ok(CountryISO::DOM),
        "ECU" => Ok(CountryISO::ECU),
        "EGY" => Ok(CountryISO::EGY),
        "SLV" => Ok(CountryISO::SLV),
        "GNQ" => Ok(CountryISO::GNQ),
        "ERI" => Ok(CountryISO::ERI),
        "EST" => Ok(CountryISO::EST),
        "SWZ" => Ok(CountryISO::SWZ),
        "ETH" => Ok(CountryISO::ETH),
        "FJI" => Ok(CountryISO::FJI),
        "FIN" => Ok(CountryISO::FIN),
        "FRA" => Ok(CountryISO::FRA),
        "GAB" => Ok(CountryISO::GAB),
        "GMB" => Ok(CountryISO::GMB),
        "GEO" => Ok(CountryISO::GEO),
        "DEU" => Ok(CountryISO::DEU),
        "GHA" => Ok(CountryISO::GHA),
        "GRC" => Ok(CountryISO::GRC),
        "GRD" => Ok(CountryISO::GRD),
        "GTM" => Ok(CountryISO::GTM),
        "GIN" => Ok(CountryISO::GIN),
        "GNB" => Ok(CountryISO::GNB),
        "GUY" => Ok(CountryISO::GUY),
        "HKG" => Ok(CountryISO::HKG),
        "HTI" => Ok(CountryISO::HTI),
        "HND" => Ok(CountryISO::HND),
        "HUN" => Ok(CountryISO::HUN),
        "ISL" => Ok(CountryISO::ISL),
        "IND" => Ok(CountryISO::IND),
        "IDN" => Ok(CountryISO::IDN),
        "IRN" => Ok(CountryISO::IRN),
        "IRQ" => Ok(CountryISO::IRQ),
        "IRL" => Ok(CountryISO::IRL),
        "ISR" => Ok(CountryISO::ISR),
        "ITA" => Ok(CountryISO::ITA),
        "JAM" => Ok(CountryISO::JAM),
        "JPN" => Ok(CountryISO::JPN),
        "JOR" => Ok(CountryISO::JOR),
        "KAZ" => Ok(CountryISO::KAZ),
        "KEN" => Ok(CountryISO::KEN),
        "KIR" => Ok(CountryISO::KIR),
        "KWT" => Ok(CountryISO::KWT),
        "KGZ" => Ok(CountryISO::KGZ),
        "LAO" => Ok(CountryISO::LAO),
        "LVA" => Ok(CountryISO::LVA),
        "LBN" => Ok(CountryISO::LBN),
        "LSO" => Ok(CountryISO::LSO),
        "LBR" => Ok(CountryISO::LBR),
        "LBY" => Ok(CountryISO::LBY),
        "LIE" => Ok(CountryISO::LIE),
        "LTU" => Ok(CountryISO::LTU),
        "LUX" => Ok(CountryISO::LUX),
        "MDG" => Ok(CountryISO::MDG),
        "MWI" => Ok(CountryISO::MWI),
        "MYS" => Ok(CountryISO::MYS),
        "MDV" => Ok(CountryISO::MDV),
        "MLI" => Ok(CountryISO::MLI),
        "MLT" => Ok(CountryISO::MLT),
        "MHL" => Ok(CountryISO::MHL),
        "MRT" => Ok(CountryISO::MRT),
        "MUS" => Ok(CountryISO::MUS),
        "MEX" => Ok(CountryISO::MEX),
        "FSM" => Ok(CountryISO::FSM),
        "MDA" => Ok(CountryISO::MDA),
        "MCO" => Ok(CountryISO::MCO),
        "MNG" => Ok(CountryISO::MNG),
        "MNE" => Ok(CountryISO::MNE),
        "MAR" => Ok(CountryISO::MAR),
        "MOZ" => Ok(CountryISO::MOZ),
        "MMR" => Ok(CountryISO::MMR),
        "NAM" => Ok(CountryISO::NAM),
        "NRU" => Ok(CountryISO::NRU),
        "NPL" => Ok(CountryISO::NPL),
        "NLD" => Ok(CountryISO::NLD),
        "NZL" => Ok(CountryISO::NZL),
        "NIC" => Ok(CountryISO::NIC),
        "NER" => Ok(CountryISO::NER),
        "NGA" => Ok(CountryISO::NGA),
        "MKD" => Ok(CountryISO::MKD),
        "NOR" => Ok(CountryISO::NOR),
        "OMN" => Ok(CountryISO::OMN),
        "PAK" => Ok(CountryISO::PAK),
        "PLW" => Ok(CountryISO::PLW),
        "PAN" => Ok(CountryISO::PAN),
        "PNG" => Ok(CountryISO::PNG),
        "PRY" => Ok(CountryISO::PRY),
        "PER" => Ok(CountryISO::PER),
        "PHL" => Ok(CountryISO::PHL),
        "POL" => Ok(CountryISO::POL),
        "PRT" => Ok(CountryISO::PRT),
        "QAT" => Ok(CountryISO::QAT),
        "KOR" => Ok(CountryISO::KOR),
        "ROU" => Ok(CountryISO::ROU),
        "RUS" => Ok(CountryISO::RUS),
        "RWA" => Ok(CountryISO::RWA),
        "KNA" => Ok(CountryISO::KNA),
        "LCA" => Ok(CountryISO::LCA),
        "VCT" => Ok(CountryISO::VCT),
        "WSM" => Ok(CountryISO::WSM),
        "SMR" => Ok(CountryISO::SMR),
        "STP" => Ok(CountryISO::STP),
        "SAU" => Ok(CountryISO::SAU),
        "SEN" => Ok(CountryISO::SEN),
        "SRB" => Ok(CountryISO::SRB),
        "SYC" => Ok(CountryISO::SYC),
        "SLE" => Ok(CountryISO::SLE),
        "SGP" => Ok(CountryISO::SGP),
        "SVK" => Ok(CountryISO::SVK),
        "SVN" => Ok(CountryISO::SVN),
        "SLB" => Ok(CountryISO::SLB),
        "SOM" => Ok(CountryISO::SOM),
        "ZAF" => Ok(CountryISO::ZAF),
        "SSD" => Ok(CountryISO::SSD),
        "ESP" => Ok(CountryISO::ESP),
        "LKA" => Ok(CountryISO::LKA),
        "SDN" => Ok(CountryISO::SDN),
        "SUR" => Ok(CountryISO::SUR),
        "SWE" => Ok(CountryISO::SWE),
        "CHE" => Ok(CountryISO::CHE),
        "SYR" => Ok(CountryISO::SYR),
        "TJK" => Ok(CountryISO::TJK),
        "TZA" => Ok(CountryISO::TZA),
        "THA" => Ok(CountryISO::THA),
        "TLS" => Ok(CountryISO::TLS),
        "TGO" => Ok(CountryISO::TGO),
        "TON" => Ok(CountryISO::TON),
        "TTO" => Ok(CountryISO::TTO),
        "TUN" => Ok(CountryISO::TUN),
        "TUR" => Ok(CountryISO::TUR),
        "TKM" => Ok(CountryISO::TKM),
        "TUV" => Ok(CountryISO::TUV),
        "UGA" => Ok(CountryISO::UGA),
        "UKR" => Ok(CountryISO::UKR),
        "ARE" => Ok(CountryISO::ARE),
        "GBR" => Ok(CountryISO::GBR),
        "USA" => Ok(CountryISO::USA),
        "URY" => Ok(CountryISO::URY),
        "UZB" => Ok(CountryISO::UZB),
        "VUT" => Ok(CountryISO::VUT),
        "VEN" => Ok(CountryISO::VEN),
        "VNM" => Ok(CountryISO::VNM),
        "YEM" => Ok(CountryISO::YEM),
        "ZMB" => Ok(CountryISO::ZMB),
        "ZWE" => Ok(CountryISO::ZWE),
        "ATG" => Ok(CountryISO::ATG),
        _ => Err(ApiError::ParsingError("Invalid Country ISO")),
    }
}

#[derive(Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Clone, Copy)]
pub enum CountryISO2 {
    AD,
    AE,
    AF,
    AI,
    AL,
    AM,
    AO,
    AR,
    AS,
    AT,
    AU,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BN,
    BO,
    BR,
    BS,
    BT,
    BW,
    BY,
    BZ,
    CA,
    CD,
    CF,
    CG,
    CH,
    CI,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FM,
    FR,
    GA,
    GB,
    GD,
    GE,
    GH,
    GM,
    GN,
    GQ,
    GR,
    GT,
    GW,
    GY,
    HK,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IN,
    IQ,
    IR,
    IS,
    IT,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MG,
    MH,
}