use serde::{Deserialize, Serialize};

use crate::error::ApiError;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Currency {
    AED,
    ALL,
    AMD,
    ARS,
    AUD,
    AWG,
    AZN,
    BBD,
    BDT,
    BHD,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BWP,
    BZD,
    CAD,
    CHF,
    CNY,
    COP,
    CRC,
    CUP,
    CZK,
    DKK,
    DOP,
    DZD,
    EGP,
    ETB,
    EUR,
    FJD,
    GBP,
    GHS,
    GIP,
    GMD,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    MAD,
    MDL,
    MKD,
    MMK,
    MNT,
    MOP,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    QAR,
    RUB,
    SAR,
    SCR,
    SEK,
    SGD,
    SLL,
    SOS,
    SSP,
    SVC,
    SZL,
    THB,
    TTD,
    TWD,
    TZS,
    USD,
    UYU,
    UZS,
    YER,
    ZAR,
    TRY,
    AFN,
    ANG,
    AOA,
    BAM,
    BGN,
    BIF,
    BOV,
    BTN,
    BYN,
    CDF,
    CHE,
    CHW,
    CLF,
    CLP,
    COU,
    CUC,
    CVE,
    DJF,
    ERN,
    FKP,
    GEL,
    GNF,
    IQD,
    IRR,
    ISK,
    KMF,
    KPW,
    LYD,
    MGA,
    MRO,
    MXV,
    MZN,
    PAB,
    PYG,
    RSD,
    RWF,
    SBD,
    SDG,
    SHP,
    SRD,
    STD,
    SYP,
    TJS,
    TMT,
    TND,
    TOP,
    UAH,
    UGX,
    USN,
    UYI,
    VEF,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XSU,
    XTS,
    XUA,
    XXX,
    ZMW,
    ZWL,
}

impl Currency {
    pub fn to_text(&self) -> &str {
        match self {
            Currency::AED => "AED",
            Currency::ALL => "ALL",
            Currency::AMD => "AMD",
            Currency::ARS => "ARS",
            Currency::AUD => "AUD",
            Currency::AWG => "AWG",
            Currency::AZN => "AZN",
            Currency::BBD => "BBD",
            Currency::BDT => "BDT",
            Currency::BHD => "BHD",
            Currency::BMD => "BMD",
            Currency::BND => "BND",
            Currency::BOB => "BOB",
            Currency::BRL => "BRL",
            Currency::BSD => "BSD",
            Currency::BWP => "BWP",
            Currency::BZD => "BZD",
            Currency::CAD => "CAD",
            Currency::CHF => "CHF",
            Currency::CNY => "CNY",
            Currency::COP => "COP",
            Currency::CRC => "CRC",
            Currency::CUP => "CUP",
            Currency::CZK => "CZK",
            Currency::DKK => "DKK",
            Currency::DOP => "DOP",
            Currency::DZD => "DZD",
            Currency::EGP => "EGP",
            Currency::ETB => "ETB",
            Currency::EUR => "EUR",
            Currency::FJD => "FJD",
            Currency::GBP => "GBP",
            Currency::GHS => "GHS",
            Currency::GIP => "GIP",
            Currency::GMD => "GMD",
            Currency::GTQ => "GTQ",
            Currency::GYD => "GYD",
            Currency::HKD => "HKD",
            Currency::HNL => "HNL",
            Currency::HRK => "HRK",
            Currency::HTG => "HTG",
            Currency::HUF => "HUF",
            Currency::IDR => "IDR",
            Currency::ILS => "ILS",
            Currency::INR => "INR",
            Currency::JMD => "JMD",
            Currency::JOD => "JOD",
            Currency::JPY => "JPY",
            Currency::KES => "KES",
            Currency::KGS => "KGS",
            Currency::KHR => "KHR",
            Currency::KRW => "KRW",
            Currency::KWD => "KWD",
            Currency::KYD => "KYD",
            Currency::KZT => "KZT",
            Currency::LAK => "LAK",
            Currency::LBP => "LBP",
            Currency::LKR => "LKR",
            Currency::LRD => "LRD",
            Currency::LSL => "LSL",
            Currency::MAD => "MAD",
            Currency::MDL => "MDL",
            Currency::MKD => "MKD",
            Currency::MMK => "MMK",
            Currency::MNT => "MNT",
            Currency::MOP => "MOP",
            Currency::MUR => "MUR",
            Currency::MVR => "MVR",
            Currency::MWK => "MWK",
            Currency::MXN => "MXN",
            Currency::MYR => "MYR",
            Currency::NAD => "NAD",
            Currency::NGN => "NGN",
            Currency::NIO => "NIO",
            Currency::NOK => "NOK",
            Currency::NPR => "NPR",
            Currency::NZD => "NZD",
            Currency::OMR => "OMR",
            Currency::PEN => "PEN",
            Currency::PGK => "PGK",
            Currency::PHP => "PHP",
            Currency::PKR => "PKR",
            Currency::PLN => "PLN",
            Currency::QAR => "QAR",
            Currency::RUB => "RUB",
            Currency::SAR => "SAR",
            Currency::SCR => "SCR",
            Currency::SEK => "SEK",
            Currency::SGD => "SGD",
            Currency::SLL => "SLL",
            Currency::SOS => "SOS",
            Currency::SSP => "SSP",
            Currency::SVC => "SVC",
            Currency::SZL => "SZL",
            Currency::THB => "THB",
            Currency::TTD => "TTD",
            Currency::TWD => "TWD",
            Currency::TZS => "TZS",
            Currency::USD => "USD",
            Currency::UYU => "UYU",
            Currency::UZS => "UZS",
            Currency::YER => "YER",
            Currency::ZAR => "ZAR",
            Currency::TRY => "TRY",
            Currency::AFN => "AFN",
            Currency::ANG => "ANG",
            Currency::AOA => "AOA",
            Currency::BAM => "BAM",
            Currency::BGN => "BGN",
            Currency::BIF => "BIF",
            Currency::BOV => "BOV",
            Currency::BTN => "BTN",
            Currency::BYN => "BYN",
            Currency::CDF => "CDF",
            Currency::CHE => "CHE",
            Currency::CHW => "CHW",
            Currency::CLF => "CLF",
            Currency::CLP => "CLP",
            Currency::COU => "COU",
            Currency::CUC => "CUC",
            Currency::CVE => "CVE",
            Currency::DJF => "DJF",
            Currency::ERN => "ERN",
            Currency::FKP => "FKP",
            Currency::GEL => "GEL",
            Currency::GNF => "GNF",
            Currency::IQD => "IQD",
            Currency::IRR => "IRR",
            Currency::ISK => "ISK",
            Currency::KMF => "KMF",
            Currency::KPW => "KPW",
            Currency::LYD => "LYD",
            Currency::MGA => "MGA",
            Currency::MRO => "MRO",
            Currency::MXV => "MXV",
            Currency::MZN => "MZN",
            Currency::PAB => "PAB",
            Currency::PYG => "PYG",
            Currency::RSD => "RSD",
            Currency::RWF => "RWF",
            Currency::SBD => "SBD",
            Currency::SDG => "SDG",
            Currency::SHP => "SHP",
            Currency::SRD => "SRD",
            Currency::STD => "STD",
            Currency::SYP => "SYP",
            Currency::TJS => "TJS",
            Currency::TMT => "TMT",
            Currency::TND => "TND",
            Currency::TOP => "TOP",
            Currency::UAH => "UAH",
            Currency::UGX => "UGX",
            Currency::USN => "USN",
            Currency::UYI => "UYI",
            Currency::VEF => "VEF",
            Currency::VND => "VND",
            Currency::VUV => "VUV",
            Currency::WST => "WST",
            Currency::XAF => "XAF",
            Currency::XAG => "XAG",
            Currency::XAU => "XAU",
            Currency::XBA => "XBA",
            Currency::XBB => "XBB",
            Currency::XBC => "XBC",
            Currency::XBD => "XBD",
            Currency::XCD => "XCD",
            Currency::XDR => "XDR",
            Currency::XOF => "XOF",
            Currency::XPD => "XPD",
            Currency::XPF => "XPF",
            Currency::XPT => "XPT",
            Currency::XSU => "XSU",
            Currency::XTS => "XTS",
            Currency::XUA => "XUA",
            Currency::XXX => "XXX",
            Currency::ZMW => "ZMW",
            Currency::ZWL => "ZWL",
        }
    }

    pub fn text_to_curr(text: &str) -> Result<Currency, ApiError> {
        match text {
            "AED" => Ok(Currency::AED),
            "ALL" => Ok(Currency::ALL),
            "AMD" => Ok(Currency::AMD),
            "ARS" => Ok(Currency::ARS),
            "AUD" => Ok(Currency::AUD),
            "AWG" => Ok(Currency::AWG),
            "AZN" => Ok(Currency::AZN),
            "BBD" => Ok(Currency::BBD),
            "BDT" => Ok(Currency::BDT),
            "BHD" => Ok(Currency::BHD),
            "BMD" => Ok(Currency::BMD),
            "BND" => Ok(Currency::BND),
            "BOB" => Ok(Currency::BOB),
            "BRL" => Ok(Currency::BRL),
            "BSD" => Ok(Currency::BSD),
            "BWP" => Ok(Currency::BWP),
            "BZD" => Ok(Currency::BZD),
            "CAD" => Ok(Currency::CAD),
            "CHF" => Ok(Currency::CHF),
            "CNY" => Ok(Currency::CNY),
            "COP" => Ok(Currency::COP),
            "CRC" => Ok(Currency::CRC),
            "CUP" => Ok(Currency::CUP),
            "CZK" => Ok(Currency::CZK),
            "DKK" => Ok(Currency::DKK),
            "DOP" => Ok(Currency::DOP),
            "DZD" => Ok(Currency::DZD),
            "EGP" => Ok(Currency::EGP),
            "ETB" => Ok(Currency::ETB),
            "EUR" => Ok(Currency::EUR),
            "FJD" => Ok(Currency::FJD),
            "GBP" => Ok(Currency::GBP),
            "GHS" => Ok(Currency::GHS),
            "GIP" => Ok(Currency::GIP),
            "GMD" => Ok(Currency::GMD),
            "GTQ" => Ok(Currency::GTQ),
            "GYD" => Ok(Currency::GYD),
            "HKD" => Ok(Currency::HKD),
            "HNL" => Ok(Currency::HNL),
            "HRK" => Ok(Currency::HRK),
            "HTG" => Ok(Currency::HTG),
            "HUF" => Ok(Currency::HUF),
            "IDR" => Ok(Currency::IDR),
            "ILS" => Ok(Currency::ILS),
            "INR" => Ok(Currency::INR),
            "JMD" => Ok(Currency::JMD),
            "JOD" => Ok(Currency::JOD),
            "JPY" => Ok(Currency::JPY),
            "KES" => Ok(Currency::KES),
            "KGS" => Ok(Currency::KGS),
            "KHR" => Ok(Currency::KHR),
            "KRW" => Ok(Currency::KRW),
            "KWD" => Ok(Currency::KWD),
            "KYD" => Ok(Currency::KYD),
            "KZT" => Ok(Currency::KZT),
            "LAK" => Ok(Currency::LAK),
            "LBP" => Ok(Currency::LBP),
            "LKR" => Ok(Currency::LKR),
            "LRD" => Ok(Currency::LRD),
            "LSL" => Ok(Currency::LSL),
            "MAD" => Ok(Currency::MAD),
            "MDL" => Ok(Currency::MDL),
            "MKD" => Ok(Currency::MKD),
            "MMK" => Ok(Currency::MMK),
            "MNT" => Ok(Currency::MNT),
            "MOP" => Ok(Currency::MOP),
            "MUR" => Ok(Currency::MUR),
            "MVR" => Ok(Currency::MVR),
            "MWK" => Ok(Currency::MWK),
            "MXN" => Ok(Currency::MXN),
            "MYR" => Ok(Currency::MYR),
            "NAD" => Ok(Currency::NAD),
            "NGN" => Ok(Currency::NGN),
            "NIO" => Ok(Currency::NIO),
            "NOK" => Ok(Currency::NOK),
            "NPR" => Ok(Currency::NPR),
            "NZD" => Ok(Currency::NZD),
            "OMR" => Ok(Currency::OMR),
            "PEN" => Ok(Currency::PEN),
            "PGK" => Ok(Currency::PGK),
            "PHP" => Ok(Currency::PHP),
            "PKR" => Ok(Currency::PKR),
            "PLN" => Ok(Currency::PLN),
            "QAR" => Ok(Currency::QAR),
            "RUB" => Ok(Currency::RUB),
            "SAR" => Ok(Currency::SAR),
            "SCR" => Ok(Currency::SCR),
            "SEK" => Ok(Currency::SEK),
            "SGD" => Ok(Currency::SGD),
            "SLL" => Ok(Currency::SLL),
            "SOS" => Ok(Currency::SOS),
            "SSP" => Ok(Currency::SSP),
            "SVC" => Ok(Currency::SVC),
            "SZL" => Ok(Currency::SZL),
            "THB" => Ok(Currency::THB),
            "TTD" => Ok(Currency::TTD),
            "TWD" => Ok(Currency::TWD),
            "TZS" => Ok(Currency::TZS),
            "USD" => Ok(Currency::USD),
            "UYU" => Ok(Currency::UYU),
            "UZS" => Ok(Currency::UZS),
            "YER" => Ok(Currency::YER),
            "ZAR" => Ok(Currency::ZAR),
            "TRY" => Ok(Currency::TRY),
            "AFN" => Ok(Currency::AFN),
            "ANG" => Ok(Currency::ANG),
            "AOA" => Ok(Currency::AOA),
            "BAM" => Ok(Currency::BAM),
            "BGN" => Ok(Currency::BGN),
            "BIF" => Ok(Currency::BIF),
            "BOV" => Ok(Currency::BOV),
            "BTN" => Ok(Currency::BTN),
            "BYN" => Ok(Currency::BYN),
            "CDF" => Ok(Currency::CDF),
            "CHE" => Ok(Currency::CHE),
            "CHW" => Ok(Currency::CHW),
            "CLF" => Ok(Currency::CLF),
            "CLP" => Ok(Currency::CLP),
            "COU" => Ok(Currency::COU),
            "CUC" => Ok(Currency::CUC),
            "CVE" => Ok(Currency::CVE),
            "DJF" => Ok(Currency::DJF),
            "ERN" => Ok(Currency::ERN),
            "FKP" => Ok(Currency::FKP),
            "GEL" => Ok(Currency::GEL),
            "GNF" => Ok(Currency::GNF),
            "IQD" => Ok(Currency::IQD),
            "IRR" => Ok(Currency::IRR),
            "ISK" => Ok(Currency::ISK),
            "KMF" => Ok(Currency::KMF),
            "KPW" => Ok(Currency::KPW),
            "LYD" => Ok(Currency::LYD),
            "MGA" => Ok(Currency::MGA),
            "MRO" => Ok(Currency::MRO),
            "MXV" => Ok(Currency::MXV),
            "MZN" => Ok(Currency::MZN),
            "PAB" => Ok(Currency::PAB),
            "PYG" => Ok(Currency::PYG),
            "RSD" => Ok(Currency::RSD),
            "RWF" => Ok(Currency::RWF),
            "SBD" => Ok(Currency::SBD),
            "SDG" => Ok(Currency::SDG),
            "SHP" => Ok(Currency::SHP),
            "SRD" => Ok(Currency::SRD),
            "STD" => Ok(Currency::STD),
            "SYP" => Ok(Currency::SYP),
            "TJS" => Ok(Currency::TJS),
            "TMT" => Ok(Currency::TMT),
            "TND" => Ok(Currency::TND),
            "TOP" => Ok(Currency::TOP),
            "UAH" => Ok(Currency::UAH),
            "UGX" => Ok(Currency::UGX),
            "USN" => Ok(Currency::USN),
            "UYI" => Ok(Currency::UYI),
            "VEF" => Ok(Currency::VEF),
            "VND" => Ok(Currency::VND),
            "VUV" => Ok(Currency::VUV),
            "WST" => Ok(Currency::WST),
            "XAF" => Ok(Currency::XAF),
            "XAG" => Ok(Currency::XAG),
            "XAU" => Ok(Currency::XAU),

            "XBA" => Ok(Currency::XBA),
            "XBB" => Ok(Currency::XBB),
            "XBC" => Ok(Currency::XBC),
            "XBD" => Ok(Currency::XBD),
            "XCD" => Ok(Currency::XCD),
            "XDR" => Ok(Currency::XDR),
            "XOF" => Ok(Currency::XOF),
            "XPD" => Ok(Currency::XPD),
            "XPF" => Ok(Currency::XPF),
            "XPT" => Ok(Currency::XPT),
            "XSU" => Ok(Currency::XSU),
            "XTS" => Ok(Currency::XTS),
            "XUA" => Ok(Currency::XUA),
            "XXX" => Ok(Currency::XXX),
            "ZMW" => Ok(Currency::ZMW),
            "ZWL" => Ok(Currency::ZWL),
            _ => Err(ApiError::ParsingError("Invalid Currency")),
        }
    }
}
