use serde::{Serialize, Deserialize};
use serde_json::Value as AValue;
use std::collections::HashMap;
use std::string::String;
use std::vec::Vec;
use std::option::Option;
use std::fmt;
use std::hash::Hash;
use std::str::FromStr;

use crate::error::ApiError;

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Serialize, Deserialize, Eq, Hash)]
pub enum Gateway {
    ADYEN,
    AFTERPAY,
    AIRPAY,
    PAYPHI,
    AIRTELMONEY,
    AIRWALLEX,
    AMAZONPAY,
    AMEX,
    AMPS,
    ATOM,
    AUTHORIZEDOTNET,
    AXIS,
    AXIS_BIZ,
    AXIS_UPI,
    AXISNB,
    BAJAJFINSERV,
    BHARATX,
    BILLDESK,
    BLAZEPAY,
    BRAINTREE,
    BOKU,
    CAMSPAY,
    CAPILLARY,
    CAPITALFLOAT,
    CAREEMPAY,
    CASH,
    CASHTOCODE,
    CCAVENUE,
    CCAVENUE_V2,
    CHECKOUT,
    CIELO,
    CITI,
    CITRUS,
    CRED,
    CYBERSOURCE,
    CYBS_CHASE,
    DIGIO,
    DIRECT_BANK_EMI,
    DLOCAL,
    DUMMY,
    EARLYSALARY,
    EASEBUZZ,
    EBANX,
    EBS,
    EBS_V3,
    EPAYLATER,
    EXPRESSPG,
    FACILITAPAY,
    FASPAY,
    FEDERAL_BIZ,
    FDCONNECT,
    FIB,
    FINBOX,
    FLEXMONEY,
    FLUTTERWAVE,
    FREECHARGE,
    FREECHARGEPG,
    FREECHARGE_V2,
    FSS_ATM_PIN,
    FSS_ATM_PIN_V2,
    FSSPAY,
    GOCASHFREE,
    GOKWIK,
    GOOGLEPAY,
    GPAY_IMF,
    GYFTR,
    HDFC,
    HDFC_DC_EMI,
    HDFC_CC_EMI,
    HDFC_EBS_VAS,
    HDFC_FLEXIPAY,
    HDFC_IVR,
    HDFCBANK_SMARTGATEWAY,
    HDFC_UPI,
    HDFCNB,
    HSBC,
    HSBC_UPI,
    HYPERPAY,
    HYPERPG,
    HYPER_PG,
    IATAPAY,
    ICICI,
    ICICI_UPI,
    ICICINB,
    ICICIPAYLATER,
    IFG,
    INDUS_UPI,
    INSPIRE_NETZ,
    INSTACRED,
    INDUS_PAYU,
    IPG,
    ITAU,
    ITZCASH,
    JIOMONEY,
    JIOPAY,
    KBANK,
    KLARNA,
    KOTAK,
    KOTAK_BIZ,
    KOTAK_UPI,
    LAZYPAY,
    LINEPAY,
    LOANTAP,
    LOTUSPAY,
    LOYLTYREWARDZ,
    LSP,
    LSP_ETB,
    LYRA,
    M2P,
    MERCADOPAGO,
    MERCHANT_CONTAINER,
    MIDTRANS,
    MIGS,
    MOBIKWIK,
    MOBIKWIKZIP,
    MORPHEUS,
    MPESA,
    MPGS,
    MSWIPE,
    MYFATOORAH,
    TAPPAY,
    TAZAPAY,
    PAYMOB,
    FAWRYPAY,
    NAVITAIRE,
    NBBL,
    MOSAMBEE,
    NETCETERA,
    NMI,
    NOON,
    NONE,
    NUPAY,
    OLAMONEY,
    OLAPOSTPAID,
    ONEPAY,
    OPNPAYMENTS,
    PAGALEVE,
    PAGSEGURO,
    PAYAMIGO,
    PAYFORT,
    PAYGLOCAL,
    PAYLATER,
    PAYPAL,
    PAYTM,
    PAYTM_UPI,
    PAYTM_V2,
    PAYU,
    PAYZAPP,
    PHONEPE,
    PINELABS,
    PINELABS_OFFLINE,
    POSTPAY,
    QWIKCILVER,
    RAZORPAY,
    RBL,
    RBL_BIZ,
    SBI,
    SBI_UPI,
    SBIBUDDY,
    SBIePAY,
    SEZZLE,
    SHOPSE,
    SIKA_SIMPL,
    SIMPL,
    SNAPMINT,
    SODEXO,
    STRIPE,
    TABBY,
    TATA_PA,
    TATA_UPI,
    TATANEU,
    TATAPAY,
    TATAPAYLATER,
    TAP,
    TPSL,
    TPSL_SI,
    TRIPLEA,
    TRUSTPAY,
    TWID,
    TWID_V2,
    TWOC_TWOP,
    VIJAYA_UPI,
    VOLT,
    VISA_PBW,
    WALLET_CONTAINER,
    WORLDPAY,
    XENDIT,
    YES_BIZ,
    YESBANK_UPI,
    YPP,
    ZAAKPAY,
    ZESTMONEY,
    DOKU,
    ZAINCASH,
    FASTPAY,
    PAY10,
    PINELABS_ONLINE,
    WIBMO,
    NDPS,
    DEFAULT,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum GatewayAny {
    GatewayKnown(Gateway),
    GatewayUnknown,
}

impl fmt::Display for GatewayAny {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match gateway_any_to_text(self) {
            Some(text) => write!(f, "{}", text),
            None => write!(f, "UnknownGateway"),
        }
    }
}

pub fn gateway_any_to_text(gateway_any: &GatewayAny) -> Option<String> {
    match gateway_any {
        GatewayAny::GatewayKnown(gateway) => Some(gateway_to_text(gateway)),
        GatewayAny::GatewayUnknown => None,
    }
}

pub fn gateway_to_text(gateway: &Gateway) -> String {
    format!("{:?}", gateway)
}

pub fn text_to_gateway(text: &str) -> Result<Gateway, ApiError> {
    match text {
        "ADYEN" => Ok(Gateway::ADYEN),
        "AFTERPAY" => Ok(Gateway::AFTERPAY),
        "AIRPAY" => Ok(Gateway::AIRPAY),
        "PAYPHI" => Ok(Gateway::PAYPHI),
        "AIRTELMONEY" => Ok(Gateway::AIRTELMONEY),
        "AIRWALLEX" => Ok(Gateway::AIRWALLEX),
        "AMAZONPAY" => Ok(Gateway::AMAZONPAY),
        "AMEX" => Ok(Gateway::AMEX),
        "AMPS" => Ok(Gateway::AMPS),
        "ATOM" => Ok(Gateway::ATOM),
        "AUTHORIZEDOTNET" => Ok(Gateway::AUTHORIZEDOTNET),
        "AXIS_BIZ" => Ok(Gateway::AXIS_BIZ),
        "AXIS_UPI" => Ok(Gateway::AXIS_UPI),
        "AXIS" => Ok(Gateway::AXIS),
        "AXISNB" => Ok(Gateway::AXISNB),
        "BAJAJFINSERV" => Ok(Gateway::BAJAJFINSERV),
        "BHARATX" => Ok(Gateway::BHARATX),
        "BILLDESK" => Ok(Gateway::BILLDESK),
        "BLAZEPAY" => Ok(Gateway::BLAZEPAY),
        "BRAINTREE" => Ok(Gateway::BRAINTREE),
        "BOKU" => Ok(Gateway::BOKU),
        "CAMSPAY" => Ok(Gateway::CAMSPAY),
        "CAPILLARY" => Ok(Gateway::CAPILLARY),
        "CAPITALFLOAT" => Ok(Gateway::CAPITALFLOAT),
        "CAREEMPAY" => Ok(Gateway::CAREEMPAY),
        "CASH" => Ok(Gateway::CASH),
        "CASHTOCODE" => Ok(Gateway::CASHTOCODE),
        "CCAVENUE_V2" => Ok(Gateway::CCAVENUE_V2),
        "CCAVENUE" => Ok(Gateway::CCAVENUE),
        "CHECKOUT" => Ok(Gateway::CHECKOUT),
        "CIELO" => Ok(Gateway::CIELO),
        "CITI" => Ok(Gateway::CITI),
        "CITRUS" => Ok(Gateway::CITRUS),
        "CRED" => Ok(Gateway::CRED),
        "CYBERSOURCE" => Ok(Gateway::CYBERSOURCE),
        "CYBS_CHASE" => Ok(Gateway::CYBS_CHASE),
        "DIGIO" => Ok(Gateway::DIGIO),
        "DLOCAL" => Ok(Gateway::DLOCAL),
        "DUMMY" => Ok(Gateway::DUMMY),
        "EARLYSALARY" => Ok(Gateway::EARLYSALARY),
        "EASEBUZZ" => Ok(Gateway::EASEBUZZ),
        "EBANX" => Ok(Gateway::EBANX),
        "EBS_V3" => Ok(Gateway::EBS_V3),
        "EBS" => Ok(Gateway::EBS),
        "EPAYLATER" => Ok(Gateway::EPAYLATER),
        "EXPRESSPG" => Ok(Gateway::EXPRESSPG),
        "FACILITAPAY" => Ok(Gateway::FACILITAPAY),
        "FASPAY" => Ok(Gateway::FASPAY),
        "FASTPAY" => Ok(Gateway::FASTPAY),
        "FEDERAL_BIZ" => Ok(Gateway::FEDERAL_BIZ),
        "FDCONNECT" => Ok(Gateway::FDCONNECT),
        "FIB" => Ok(Gateway::FIB),
        "FINBOX" => Ok(Gateway::FINBOX),
        "FLEXMONEY" => Ok(Gateway::FLEXMONEY),
        "FLUTTERWAVE" => Ok(Gateway::FLUTTERWAVE),
        "FREECHARGE_V2" => Ok(Gateway::FREECHARGE_V2),
        "FREECHARGEPG" => Ok(Gateway::FREECHARGEPG),
        "FREECHARGE" => Ok(Gateway::FREECHARGE),
        "FSS_ATM_PIN_V2" => Ok(Gateway::FSS_ATM_PIN_V2),
        "FSS_ATM_PIN" => Ok(Gateway::FSS_ATM_PIN),
        "FSSPAY" => Ok(Gateway::FSSPAY),
        "GOCASHFREE" => Ok(Gateway::GOCASHFREE),
        "GOKWIK" => Ok(Gateway::GOKWIK),
        "GOOGLEPAY" => Ok(Gateway::GOOGLEPAY),
        "GPAY_IMF" => Ok(Gateway::GPAY_IMF),
        "GYFTR" => Ok(Gateway::GYFTR),
        "HDFC_DC_EMI" => Ok(Gateway::HDFC_DC_EMI),
        "HDFC_CC_EMI" => Ok(Gateway::HDFC_CC_EMI),
        "HDFC_EBS_VAS" => Ok(Gateway::HDFC_EBS_VAS),
        "HDFC_FLEXIPAY" => Ok(Gateway::HDFC_FLEXIPAY),
        "HDFC_IVR" => Ok(Gateway::HDFC_IVR),
        "HDFCBANK_SMARTGATEWAY" => Ok(Gateway::HDFCBANK_SMARTGATEWAY),
        "HDFC_UPI" => Ok(Gateway::HDFC_UPI),
        "HDFC" => Ok(Gateway::HDFC),
        "HDFCNB" => Ok(Gateway::HDFCNB),
        "HSBC" => Ok(Gateway::HSBC),
        "HSBC_UPI" => Ok(Gateway::HSBC_UPI),
        "HYPERPG" => Ok(Gateway::HYPERPG),
        "HYPERPAY" => Ok(Gateway::HYPERPAY),
        "HYPER_PG" => Ok(Gateway::HYPER_PG),
        "IATAPAY" => Ok(Gateway::IATAPAY),
        "ICICI_UPI" => Ok(Gateway::ICICI_UPI),
        "ICICI" => Ok(Gateway::ICICI),
        "ICICINB" => Ok(Gateway::ICICINB),
        "ICICIPAYLATER" => Ok(Gateway::ICICIPAYLATER),
        "IFG" => Ok(Gateway::IFG),
        "INDUS_UPI" => Ok(Gateway::INDUS_UPI),
        "INSPIRE_NETZ" => Ok(Gateway::INSPIRE_NETZ),
        "INSTACRED" => Ok(Gateway::INSTACRED),
        "INDUS_PAYU" => Ok(Gateway::INDUS_PAYU),
        "IPG" => Ok(Gateway::IPG),
        "ITAU" => Ok(Gateway::ITAU),
        "ITZCASH" => Ok(Gateway::ITZCASH),
        "JIOMONEY" => Ok(Gateway::JIOMONEY),
        "JIOPAY" => Ok(Gateway::JIOPAY),
        "KBANK" => Ok(Gateway::KBANK),
        "KLARNA" => Ok(Gateway::KLARNA),
        "KOTAK_UPI" => Ok(Gateway::KOTAK_UPI),
        "KOTAK" => Ok(Gateway::KOTAK),
        "KOTAK_BIZ" => Ok(Gateway::KOTAK_BIZ),
        "LAZYPAY" => Ok(Gateway::LAZYPAY),
        "LINEPAY" => Ok(Gateway::LINEPAY),
        "LOANTAP" => Ok(Gateway::LOANTAP),
        "LOTUSPAY" => Ok(Gateway::LOTUSPAY),
        "LOYLTYREWARDZ" => Ok(Gateway::LOYLTYREWARDZ),
        "LSP" => Ok(Gateway::LSP),
        "LSP_ETB" => Ok(Gateway::LSP_ETB),
        "LYRA" => Ok(Gateway::LYRA),
        "M2P" => Ok(Gateway::M2P),
        "MERCADOPAGO" => Ok(Gateway::MERCADOPAGO),
        "MERCHANT_CONTAINER" => Ok(Gateway::MERCHANT_CONTAINER),
        "MIDTRANS" => Ok(Gateway::MIDTRANS),
        "MIGS" => Ok(Gateway::MIGS),
        "MOBIKWIK" => Ok(Gateway::MOBIKWIK),
        "MOBIKWIKZIP" => Ok(Gateway::MOBIKWIKZIP),
        "MORPHEUS" => Ok(Gateway::MORPHEUS),
        "MPESA" => Ok(Gateway::MPESA),
        "MPGS" => Ok(Gateway::MPGS),
        "MSWIPE" => Ok(Gateway::MSWIPE),
        "MYFATOORAH" => Ok(Gateway::MYFATOORAH),
        "TAPPAY" => Ok(Gateway::TAPPAY),
        "TAZAPAY" => Ok(Gateway::TAZAPAY),
        "PAYMOB" => Ok(Gateway::PAYMOB),
        "FAWRYPAY" => Ok(Gateway::FAWRYPAY),
        "NAVITAIRE" => Ok(Gateway::NAVITAIRE),
        "NBBL" => Ok(Gateway::NBBL),
        "MOSAMBEE" => Ok(Gateway::MOSAMBEE),
        "NETCETERA" => Ok(Gateway::NETCETERA),
        "NMI" => Ok(Gateway::NMI),
        "NOON" => Ok(Gateway::NOON),
        "NONE" => Ok(Gateway::NONE),
        "NUPAY" => Ok(Gateway::NUPAY),
        "OLAMONEY" => Ok(Gateway::OLAMONEY),
        "OLAPOSTPAID" => Ok(Gateway::OLAPOSTPAID),
        "ONEPAY" => Ok(Gateway::ONEPAY),
        "OPNPAYMENTS" => Ok(Gateway::OPNPAYMENTS),
        "PAGALEVE" => Ok(Gateway::PAGALEVE),
        "PAGSEGURO" => Ok(Gateway::PAGSEGURO),
        "PAYAMIGO" => Ok(Gateway::PAYAMIGO),
        "PAYFORT" => Ok(Gateway::PAYFORT),
        "PAYGLOCAL" => Ok(Gateway::PAYGLOCAL),
        "PAYLATER" => Ok(Gateway::PAYLATER),
        "PAYPAL" => Ok(Gateway::PAYPAL),
        "PAYTM_UPI" => Ok(Gateway::PAYTM_UPI),
        "PAYTM_V2" => Ok(Gateway::PAYTM_V2),
        "PAYTM" => Ok(Gateway::PAYTM),
        "PAYU" => Ok(Gateway::PAYU),
        "PAYZAPP" => Ok(Gateway::PAYZAPP),
        "PHONEPE" => Ok(Gateway::PHONEPE),
        "PINELABS" => Ok(Gateway::PINELABS),
        "PINELABS_OFFLINE" => Ok(Gateway::PINELABS_OFFLINE),
        "POSTPAY" => Ok(Gateway::POSTPAY),
        "QWIKCILVER" => Ok(Gateway::QWIKCILVER),
        "RAZORPAY" => Ok(Gateway::RAZORPAY),
        "RBL_BIZ" => Ok(Gateway::RBL_BIZ),
        "RBL" => Ok(Gateway::RBL),
        "SBI_UPI" => Ok(Gateway::SBI_UPI),
        "SBI" => Ok(Gateway::SBI),
        "SBIBUDDY" => Ok(Gateway::SBIBUDDY),
        "SBIePAY" => Ok(Gateway::SBIePAY),
        "SEZZLE" => Ok(Gateway::SEZZLE),
        "SHOPSE" => Ok(Gateway::SHOPSE),
        "SIKA_SIMPL" => Ok(Gateway::SIKA_SIMPL),
        "SIMPL" => Ok(Gateway::SIMPL),
        "SNAPMINT" => Ok(Gateway::SNAPMINT),
        "SODEXO" => Ok(Gateway::SODEXO),
        "STRIPE" => Ok(Gateway::STRIPE),
        "TABBY"              => Ok(Gateway::TABBY),
        "TATA_PA"            => Ok(Gateway::TATA_PA),
        "TATA_UPI"           => Ok(Gateway::TATA_UPI),
        "TATANEU"            => Ok(Gateway::TATANEU),
        "TATAPAY"            => Ok(Gateway::TATAPAY),
        "TATAPAYLATER"       => Ok(Gateway::TATAPAYLATER),
        "TAP"                => Ok(Gateway::TAP),
        "TPSL_SI"            => Ok(Gateway::TPSL_SI),
        "TPSL"               => Ok(Gateway::TPSL),
        "TRIPLEA"            => Ok(Gateway::TRIPLEA),
        "TRUSTPAY"           => Ok(Gateway::TRUSTPAY),
        "TWID"               => Ok(Gateway::TWID),
        "TWID_V2"            => Ok(Gateway::TWID_V2),
        "TWOC_TWOP"          => Ok(Gateway::TWOC_TWOP),
        "VIJAYA_UPI"         => Ok(Gateway::VIJAYA_UPI),
        "VISA_PBW"           => Ok(Gateway::VISA_PBW),
        "VOLT"               => Ok(Gateway::VOLT),
        "WALLET_CONTAINER"   => Ok(Gateway::WALLET_CONTAINER),
        "WORLDPAY"           => Ok(Gateway::WORLDPAY),
        "XENDIT"             => Ok(Gateway::XENDIT),
        "YES_BIZ"            => Ok(Gateway::YES_BIZ),
        "YESBANK_UPI"        => Ok(Gateway::YESBANK_UPI),
        "YPP"                => Ok(Gateway::YPP),
        "ZAAKPAY"            => Ok(Gateway::ZAAKPAY),
        "ZESTMONEY"          => Ok(Gateway::ZESTMONEY),
        "DOKU"               => Ok(Gateway::DOKU),
        "DIRECT_BANK_EMI"    => Ok(Gateway::DIRECT_BANK_EMI),
        "ZAINCASH"           => Ok(Gateway::ZAINCASH),
        "PAY10"              => Ok(Gateway::PAY10),
        "PINELABS_ONLINE"    => Ok(Gateway::PINELABS_ONLINE),
        "WIBMO"              => Ok(Gateway::WIBMO),
        "NDPS"               => Ok(Gateway::NDPS),
        "DEFAULT"            => Ok(Gateway::DEFAULT),
        _ => Err(ApiError::ParsingError("Invalid Gateway")),
    }
}